require "__ModuleInserter__/lib"
require "__ModuleInserter__/prototypes/item"
require "__ModuleInserter__/prototypes/recipe"
require "__ModuleInserter__/prototypes/technology"
require "__ModuleInserter__/prototypes/style"
